export const defaultCategories = [
  {
    title: "Website & Technical",
    items: [
      "Basic website creation (1–5 pages)",
      "Landing page design",
      "Portfolio website creation",
      "WordPress website setup",
      "Website redesign",
      "Website speed optimization",
      "Bug fixing & small website changes",
      "Domain & hosting setup",
      "Website maintenance (monthly)",
      "Frontend development for projects",
      "Mini project development",
      "Full-stack MERN projects",
    ],
  },
  {
    title: "Design",
    items: [
      "Logo design",
      "Social media post design",
      "Poster / flyer / banner designs",
      "Business card design",
      "YouTube thumbnail design",
      "Resume / CV design",
      "PPT / presentation design",
      "Certificate & ID card design",
    ],
  },
  {
    title: "Writing & Content",
    items: [
      "Resume / CV writing",
      "Resume optimization (ATS-friendly)",
      "Cover letter writing",
      "LinkedIn profile writing",
      "Blog writing",
      "Website content writing",
      "Product description writing",
      "Email writing",
      "SOP writing",
      "Proofreading & editing",
    ],
  },
  {
    title: "Academic Support",
    items: [
      "Assignment formatting (Word / PDF)",
      "Project report formatting",
      "Lab record formatting",
      "PPT for college presentations",
      "Citation & referencing (APA / IEEE)",
      "Handwritten notes to digital PDF",
      "Notes summarization",
      "Question bank preparation",
      "Formula sheet creation",
    ],
  },
  {
    title: "AI-Based Services",
    items: [
      "AI resume rewriting",
      "AI content writing",
      "Assignment paraphrasing",
      "Plagiarism reduction",
      "AI-generated PPTs",
      "AI study notes creation",
      "ChatGPT prompt creation",
      "AI chatbot setup for websites/projects",
      "AI image generation for marketing",
      "Mock interviews using AI",
      "AI automation (basic workflows)",
    ],
  },
  {
    title: "Social & Growth",
    items: [
      "Social media account setup",
      "Instagram bio optimization",
      "Content calendar creation",
      "Caption writing & hashtag research",
      "Facebook / Instagram / Google Ads setup",
      "Influencer outreach",
      "Personal branding consultation",
    ],
  },
  {
    title: "E-commerce & Business Support",
    items: [
      "Shopify store setup",
      "Product listing & image editing",
      "Store optimization",
      "Payment gateway setup",
      "Order management support",
      "Data entry",
      "Virtual assistant services",
      "Excel / Google Sheets work",
      "Invoice creation",
      "Business profile setup",
      "Notion workspace setup",
      "Personal website/blog setup",
      "Micro-tool website development",
      "PDF tools shortlist",
    ],
  },
]

export const defaultServices = [
  {
    title: "Full-Stack MERN Projects",
    description:
      "End-to-end MERN apps with clean APIs, dashboards, and deployment.",
    includes: ["React UI", "Node/Express API", "MongoDB setup"],
    idealFor: "Startups, college projects, and business tools.",
    featured: true,
    categoryTitle: "Website & Technical",
    visible: true,
    detailTabs: [
      {
        title: "Included",
        items: [
          "React frontend for core product workflows",
          "Node and Express APIs for business logic",
          "MongoDB modeling and database setup",
          "Authentication and protected route support",
          "Admin dashboards or reporting views",
          "Testing and deployment preparation",
        ],
      },
      {
        title: "Process",
        items: [
          "Discovery to define scope and feature priorities",
          "Architecture and screen planning before build",
          "Milestone-based implementation with regular reviews",
          "Feedback cycles for refinements and approvals",
          "Staging checks before launch",
          "Deployment coordination and handoff",
        ],
      },
      {
        title: "Deliverables",
        items: [
          "Production-ready MERN application",
          "Structured source code repository",
          "Deployment setup and environment guidance",
          "Project documentation for future updates",
          "Launch checklist and verification notes",
          "Initial support after release",
        ],
      },
    ],
  },
  {
    title: "Website & Landing Pages",
    description:
      "Modern, mobile-first websites for startups, portfolios, and service businesses.",
    includes: ["1–5 page builds", "Landing pages", "Performance tuning"],
    idealFor: "Founders, creators, and small businesses.",
    featured: true,
    categoryTitle: "Website & Technical",
    visible: true,
    detailTabs: [
      {
        title: "Included",
        items: [
          "Responsive marketing pages and landing flows",
          "Conversion-focused layout and messaging support",
          "Forms, CTAs, and key section buildout",
          "Performance and mobile optimization",
          "Basic CMS or content update readiness",
          "Deployment configuration",
        ],
      },
      {
        title: "Process",
        items: [
          "Discovery on goals, audience, and offer clarity",
          "Page structure and content direction planning",
          "Design and development in clear milestones",
          "Review rounds for copy and visual polish",
          "Cross-device QA before launch",
          "Production deployment and final checks",
        ],
      },
      {
        title: "Deliverables",
        items: [
          "Production-ready website or landing page set",
          "Editable source code and asset structure",
          "Live deployment on the chosen platform",
          "Content update guidance for the team",
          "Basic technical documentation",
          "Post-launch support window",
        ],
      },
    ],
  },
  {
    title: "Frontend Development",
    description: "React-based UI delivery with clean components and fast iteration.",
    includes: ["UI builds", "Bug fixing", "Mini projects"],
    idealFor: "Product teams and students.",
    featured: true,
    categoryTitle: "Website & Technical",
    visible: true,
    detailTabs: [
      {
        title: "Included",
        items: [
          "React screens and reusable component development",
          "State handling and API integration",
          "Responsive layout implementation",
          "UI bug fixing and polish passes",
          "Accessibility and interaction improvements",
          "Frontend testing support",
        ],
      },
      {
        title: "Process",
        items: [
          "Requirements review and screen breakdown",
          "Component planning with implementation priorities",
          "Fast iteration through previewable milestones",
          "Feedback and revision loops with stakeholders",
          "Cross-browser QA before handoff",
          "Release support during deployment",
        ],
      },
      {
        title: "Deliverables",
        items: [
          "Production-ready React interface",
          "Reusable UI components and page templates",
          "Integrated frontend codebase",
          "Handoff notes for ongoing development",
          "Responsive and QA signoff updates",
          "Short post-release support",
        ],
      },
    ],
  },
  {
    title: "Design & Brand Assets",
    description:
      "Logos, social creatives, posters, and presentation design with a clean style.",
    includes: ["Logos", "Social posts", "Pitch decks"],
    idealFor: "Clubs, startups, and personal brands.",
    featured: true,
    categoryTitle: "Design",
    visible: true,
    detailTabs: [
      {
        title: "Included",
        items: [
          "Logo and brand asset design",
          "Social, poster, and deck creatives",
          "Layout and hierarchy refinement",
          "Visual system recommendations",
          "Presentation-ready file preparation",
          "Revision support within scope",
        ],
      },
      {
        title: "Process",
        items: [
          "Brief alignment on audience and visual direction",
          "Concept exploration and reference gathering",
          "Design execution with feedback checkpoints",
          "Refinement rounds on selected directions",
          "Final review for consistency and clarity",
          "Packaging for delivery and reuse",
        ],
      },
      {
        title: "Deliverables",
        items: [
          "Final approved design assets",
          "Editable source files where applicable",
          "Exported web and print-ready formats",
          "Basic usage guidance for the team",
          "Organized handoff package",
          "Support for minor launch-ready changes",
        ],
      },
    ],
  },
  {
    title: "Content & Writing",
    description:
      "Resume, LinkedIn, and website content that is clear and ATS-friendly.",
    includes: ["Resume/CV", "Cover letters", "Website copy"],
    idealFor: "Students and professionals.",
    featured: true,
    categoryTitle: "Writing & Content",
    visible: true,
    detailTabs: [
      {
        title: "Included",
        items: [
          "Resume, profile, or website content writing",
          "ATS-aware structuring and editing support",
          "Messaging clarity improvements",
          "Tone alignment for the target audience",
          "Proofreading and cleanup",
          "Revision support on approved drafts",
        ],
      },
      {
        title: "Process",
        items: [
          "Input collection on goals, role, or brand context",
          "Draft creation with structure recommendations",
          "Review round for tone and content fit",
          "Refinement based on feedback",
          "Final polish for grammar and clarity",
          "Handoff of approved copy",
        ],
      },
      {
        title: "Deliverables",
        items: [
          "Final written copy in editable format",
          "Optimized resume or profile sections",
          "Ready-to-publish website or brand messaging",
          "Suggested headlines or supporting variants",
          "Clean final version with revisions applied",
          "Usage-ready documentation or notes",
        ],
      },
    ],
  },
  {
    title: "AI Enablement",
    description:
      "Practical AI workflows: prompt setup, chatbot integration, and automation.",
    includes: ["Chatbots", "Prompt kits", "Basic automation"],
    idealFor: "Teams exploring AI safely.",
    featured: true,
    categoryTitle: "AI-Based Services",
    visible: true,
    detailTabs: [
      {
        title: "Included",
        items: [
          "Prompt workflows for repeatable tasks",
          "Chatbot or assistant setup guidance",
          "Basic automation mapping",
          "Use-case validation for team workflows",
          "Knowledge or content structuring support",
          "Practical safety and quality guardrails",
        ],
      },
      {
        title: "Process",
        items: [
          "Discovery on team goals and current bottlenecks",
          "Workflow selection for high-value automation",
          "Prototype setup and prompt refinement",
          "Review cycles with real usage feedback",
          "Documentation for repeatable execution",
          "Rollout guidance for the team",
        ],
      },
      {
        title: "Deliverables",
        items: [
          "Working prompt kit or assistant setup",
          "Automation or chatbot configuration notes",
          "Usage guidance for team adoption",
          "Recommended safeguards and escalation rules",
          "Editable documentation for future updates",
          "Initial support after implementation",
        ],
      },
    ],
  },
]

export const defaultProjects = [
  {
    name: "Global Secure Layer X",
    description: "Security-focused website with clear service messaging and fast load times.",
    domain: "IT Services",
    badgeLabel: "Security",
    accent: "green",
    icon: "ShieldCheck",
    summary:
      "Role-based access and reporting for multi-location enterprise teams with audit trail logging and compliance documentation.",
    includes: ["Role-based access control", "Audit trail logging", "Compliance documentation"],
    industry: "Cybersecurity",
    outcome: "Improved credibility and lead clarity for a security services brand.",
    idealFor: "Teams preparing for audits or enterprise requirements",
    stack: ["React", "Node.js"],
    featured: true,
    link: "https://globalsecurelayerx.in/",
  },
  {
    name: "Unicus Clothing",
    description: "Modern e-commerce storefront with clean merchandising and mobile-first UI.",
    domain: "E-Commerce",
    badgeLabel: "Retail",
    accent: "amber",
    icon: "LayoutPanelTop",
    summary:
      "Internal dashboard replacing a spreadsheet workflow for order tracking, billing reconciliation, and delivery health monitoring.",
    includes: ["Order management", "Billing reconciliation", "Delivery tracking"],
    industry: "Apparel & Retail",
    outcome: "Improved product discovery and a smoother shopping experience.",
    idealFor: "Retail teams needing visibility across orders and finance",
    stack: ["React", "Node.js"],
    featured: true,
    link: "https://unicusclothing.com/",
  },
  {
    name: "Operations Hub",
    description: "Internal dashboard to track projects, billing, and delivery health.",
    domain: "Product Engineering",
    badgeLabel: "Core",
    accent: "blue",
    icon: "Monitor",
    summary:
      "Operational control center for project delivery, billing visibility, and internal reporting across active accounts.",
    includes: ["Project tracking", "Finance visibility", "Ops reporting"],
    industry: "Professional services",
    outcome: "Improved visibility for delivery and finance teams.",
    idealFor: "Ops teams that need one shared view of delivery health",
    stack: ["React", "Node.js", "MongoDB"],
    featured: true,
    link: "https://example.com",
  },
  {
    name: "Client Intake Portal",
    description: "Secure onboarding flow with automated handoffs and status tracking.",
    domain: "Product Engineering",
    badgeLabel: "Workflow",
    accent: "pink",
    icon: "Workflow",
    summary:
      "Secure onboarding flow with automated handoffs, intake validation, and status tracking for sales and delivery teams.",
    includes: ["Intake automation", "Status tracking", "Secure handoffs"],
    industry: "B2B SaaS",
    outcome: "Faster intake and consistent handoffs for sales and delivery.",
    idealFor: "Teams reducing friction between sales and delivery",
    stack: ["React", "Express", "MongoDB"],
    featured: true,
    link: "https://example.com",
  },
  {
    name: "Service Management Suite",
    description: "Role-based access and reporting for multi-location teams.",
    domain: "Infrastructure & Scale",
    badgeLabel: "Migration",
    accent: "purple",
    icon: "Cloud",
    summary:
      "Service operations suite with reporting, role control, and environment cleanup for distributed delivery teams.",
    includes: ["Architecture redesign", "Zero-downtime cutover", "Cost monitoring setup"],
    industry: "Field services",
    outcome: "Cleaner reporting and clearer accountability across locations.",
    idealFor: "Businesses reducing technical debt and infrastructure costs",
    stack: ["React", "Node.js"],
    featured: false,
    link: "https://example.com",
  },
]

export const defaultTrendingProducts = [
  {
    title: "Resume Pro Pack",
    price: 399,
    description: "ATS-optimized resume with clean design and 2 revisions.",
    imageUrl: "https://images.unsplash.com/photo-1516382799247-87df95d790b7?auto=format&fit=crop&w=1200&q=60",
    details: ["ATS-friendly formatting", "2 revision rounds", "Editable source file"],
    active: true,
  },
  {
    title: "Portfolio Lite",
    price: 1499,
    description: "Single-page portfolio with projects, skills, and contact.",
    imageUrl: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=60",
    details: ["1-page layout", "Mobile-first design", "Deployment support"],
    active: true,
  },
  {
    title: "Personal Branding Kit",
    price: 799,
    description: "LinkedIn headline, bio, and highlight reel of skills.",
    imageUrl: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=60",
    details: ["Headline + about section", "Keyword optimization", "Profile tips"],
    active: true,
  },
  {
    title: "Personalized Gift Page",
    price: 999,
    description: "Custom page with photos, notes, and a sharable link.",
    imageUrl: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=60",
    details: ["Photo gallery", "Custom message", "Shareable link"],
    active: true,
  },
  {
    title: "Pitch Deck Design",
    price: 1299,
    description: "Modern 8–10 slide deck with your content formatted.",
    imageUrl: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=60",
    details: ["8–10 slides", "Clean visual hierarchy", "Editable PPT"],
    active: true,
  },
  {
    title: "Mini Project Build",
    price: 2499,
    description: "End-to-end mini project for college submissions.",
    imageUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=60",
    details: ["Docs + demo", "Source code", "Delivery support"],
    active: true,
  },
]

export const defaultSiteContent = {
  about: {
    heroTitle: "Small team, serious delivery",
    heroSubtitle:
      "We are a focused group of engineers and product strategists. Our work is grounded in honesty, simple execution, and measurable progress.",
    galleryImages: ["/images/about-1.svg", "/images/about-2.svg", "/images/about-3.svg"],
    highlightTitle: "Built for teams that value clarity",
    highlightSubtitle:
      "We partner with founders and ops leaders who want dependable delivery, transparent communication, and systems that scale without drama.",
    highlightPoints: [
      "Senior-led delivery with weekly checkpoints",
      "Clear scope, timelines, and measurable outcomes",
      "Practical engineering that lasts beyond launch",
    ],
    approach: [
      {
        title: "Discovery",
        description: "We define scope, outcomes, risks, and a practical roadmap.",
      },
      {
        title: "Delivery",
        description: "Weekly updates, tight feedback loops, and clear milestones.",
      },
      {
        title: "Stewardship",
        description: "We document, maintain, and improve the system after launch.",
      },
    ],
    team: [
      {
        name: "Uday Chandra",
        role: "Founder & Delivery Lead",
        bio: "Focused on clear scope, dependable execution, and long-term maintainability.",
        imageUrl: "",
      },
      {
        name: "Vaani Sharma",
        role: "Product & Client Strategy",
        bio: "Focused on clear scope, dependable execution, and long-term maintainability.",
        imageUrl: "",
      },
      {
        name: "Nitesh Pal",
        role: "Engineering & Systems",
        bio: "Focused on clear scope, dependable execution, and long-term maintainability.",
        imageUrl: "",
      },
    ],
    closingNote:
      "We work best with teams who value clear communication, respect time, and want solutions that last. If that sounds like you, we should talk.",
  },
  contact: {
    heroTitle: "Tell us about your project",
    heroSubtitle:
      "Share what you are building and what success looks like. We will reply with clear next steps, usually within one business day.",
    trustPoints: [
      "Replies within one business day",
      "No commitment required",
      "Clear scope before we start",
    ],
    formTitle: "Project inquiry",
    formStatusLabel: "Accepting projects",
    serviceFieldLabel: "Service needed",
    directTitle: "Direct contact",
    email: "hello@techservices.agency",
    whatsappUrl: "https://wa.me/1234567890",
    linkedinUrl: "",
    linkedinLabel: "VUN Tech",
    locationText: "We are based in the US and work remotely.",
    nextStepsTitle: "What happens next",
    nextSteps: [
      "We review your request and understand the brief.",
      "We confirm scope, priorities, and any open questions.",
      "You get clear next steps for moving forward.",
    ],
    requirementsTitle: "What we need from you",
    requirements: [
      "A short description of the project and what success looks like.",
      "Any existing links, docs, references, or technical context.",
      "Optional files that help us understand the work faster.",
    ],
    attachmentHint: "Optional upload: PDF, DOCX, or JPG up to 5MB.",
    linkFieldLabel: "Reference link",
  },
  home: {
    hero_title: "Build Secure Software That Scales Your Business",
    hero_subtitle: "Modern Software • AI Solutions • Cloud Infrastructure",
    hero_description:
      "We help startups and businesses design, build, and secure high-performance digital products.",
    hero_primary_button_text: "Get a Quote",
    hero_primary_button_link: "/contact",
    hero_secondary_button_text: "View Services",
    hero_secondary_button_link: "/services",
    brand_accent_color: "#2F6BFF",
    trusted_badges: [
      "Startups",
      "Small Businesses",
      "Creators",
      "Local Enterprises",
      "Early Partners",
    ],
    why_choose_items: [
      {
        icon: "Workflow",
        title: "Fast Delivery",
        description: "Rapid development cycles without compromising quality",
      },
      {
        icon: "Sparkles",
        title: "Startup-Friendly Pricing",
        description: "Affordable solutions designed for growing businesses",
      },
      {
        icon: "Code2",
        title: "Modern Tech Stack",
        description: "Built using latest secure and scalable technologies",
      },
      {
        icon: "BadgeCheck",
        title: "Direct Expert Support",
        description: "Work directly with developers, not middlemen",
      },
      {
        icon: "ShieldCheck",
        title: "Secure by Design",
        description: "Security integrated from day one",
      },
    ],
    stats: [
      { value: "20+", label: "Projects Delivered" },
      { value: "10+", label: "Technologies Used" },
      { value: "24/7", label: "Support" },
      { value: "Startup-Friendly", label: "Pricing" },
    ],
    heroCards: [],
    trustLabel: "Trusted by teams building real products -",
    trustLogos: ["Client logo", "Client logo", "Client logo", "Client logo"],
    showTestimonials: true,
    testimonials: [
      {
        quote:
          "The team kept delivery calm, structured, and transparent from start to finish.",
        name: "Operations Lead",
        role: "Multi-location services business",
      },
      {
        quote:
          "We got cleaner reporting, better visibility, and a product our team actually enjoys using.",
        name: "Founder",
        role: "E-commerce brand",
      },
      {
        quote:
          "Their execution felt senior from day one. Clear scope, solid communication, and no chaos.",
        name: "Product Manager",
        role: "Internal tools team",
      },
    ],
  },
  work: {
    heroTitle: "Case-ready work, no hype",
    heroSubtitle:
      "A sample of recent delivery across product, operations, and internal tooling. Each engagement focuses on clarity and long-term stability.",
    allProjectsLabel: "All projects",
    ctaTitle: "Want to be our next case study?",
    ctaSubtitle:
      "Every project starts with a scoping conversation. No commitment required.",
    primaryCtaLabel: "Start a project",
    primaryCtaUrl: "/contact",
    secondaryCtaLabel: "View services",
    secondaryCtaUrl: "/services",
  },
}
