export const defaultCategories = [
  {
    title: "Website & Technical",
    items: [
      "Basic website creation (1–5 pages)",
      "Landing page design",
      "Portfolio website creation",
      "WordPress website setup",
      "Website redesign",
      "Website speed optimization",
      "Bug fixing & small website changes",
      "Domain & hosting setup",
      "Website maintenance (monthly)",
      "Frontend development for projects",
      "Mini project development",
      "Full-stack MERN projects",
    ],
  },
  {
    title: "Design",
    items: [
      "Logo design",
      "Social media post design",
      "Poster / flyer / banner designs",
      "Business card design",
      "YouTube thumbnail design",
      "Resume / CV design",
      "PPT / presentation design",
      "Certificate & ID card design",
    ],
  },
  {
    title: "Writing & Content",
    items: [
      "Resume / CV writing",
      "Resume optimization (ATS-friendly)",
      "Cover letter writing",
      "LinkedIn profile writing",
      "Blog writing",
      "Website content writing",
      "Product description writing",
      "Email writing",
      "SOP writing",
      "Proofreading & editing",
    ],
  },
  {
    title: "Academic Support",
    items: [
      "Assignment formatting (Word / PDF)",
      "Project report formatting",
      "Lab record formatting",
      "PPT for college presentations",
      "Citation & referencing (APA / IEEE)",
      "Handwritten notes to digital PDF",
      "Notes summarization",
      "Question bank preparation",
      "Formula sheet creation",
    ],
  },
  {
    title: "AI-Based Services",
    items: [
      "AI resume rewriting",
      "AI content writing",
      "Assignment paraphrasing",
      "Plagiarism reduction",
      "AI-generated PPTs",
      "AI study notes creation",
      "ChatGPT prompt creation",
      "AI chatbot setup for websites/projects",
      "AI image generation for marketing",
      "Mock interviews using AI",
      "AI automation (basic workflows)",
    ],
  },
  {
    title: "Social & Growth",
    items: [
      "Social media account setup",
      "Instagram bio optimization",
      "Content calendar creation",
      "Caption writing & hashtag research",
      "Facebook / Instagram / Google Ads setup",
      "Influencer outreach",
      "Personal branding consultation",
    ],
  },
  {
    title: "E-commerce & Business Support",
    items: [
      "Shopify store setup",
      "Product listing & image editing",
      "Store optimization",
      "Payment gateway setup",
      "Order management support",
      "Data entry",
      "Virtual assistant services",
      "Excel / Google Sheets work",
      "Invoice creation",
      "Business profile setup",
      "Notion workspace setup",
      "Personal website/blog setup",
      "Micro-tool website development",
      "PDF tools shortlist",
    ],
  },
]

export const defaultServices = [
  {
    title: "Full-Stack MERN Projects",
    description:
      "End-to-end MERN apps with clean APIs, dashboards, and deployment.",
    includes: ["React UI", "Node/Express API", "MongoDB setup"],
    idealFor: "Startups, college projects, and business tools.",
    featured: true,
    categoryTitle: "Website & Technical",
    visible: true,
  },
  {
    title: "Website & Landing Pages",
    description:
      "Modern, mobile-first websites for startups, portfolios, and service businesses.",
    includes: ["1–5 page builds", "Landing pages", "Performance tuning"],
    idealFor: "Founders, creators, and small businesses.",
    featured: true,
    categoryTitle: "Website & Technical",
    visible: true,
  },
  {
    title: "Frontend Development",
    description: "React-based UI delivery with clean components and fast iteration.",
    includes: ["UI builds", "Bug fixing", "Mini projects"],
    idealFor: "Product teams and students.",
    featured: true,
    categoryTitle: "Website & Technical",
    visible: true,
  },
  {
    title: "Design & Brand Assets",
    description:
      "Logos, social creatives, posters, and presentation design with a clean style.",
    includes: ["Logos", "Social posts", "Pitch decks"],
    idealFor: "Clubs, startups, and personal brands.",
    featured: true,
    categoryTitle: "Design",
    visible: true,
  },
  {
    title: "Content & Writing",
    description:
      "Resume, LinkedIn, and website content that is clear and ATS-friendly.",
    includes: ["Resume/CV", "Cover letters", "Website copy"],
    idealFor: "Students and professionals.",
    featured: true,
    categoryTitle: "Writing & Content",
    visible: true,
  },
  {
    title: "AI Enablement",
    description:
      "Practical AI workflows: prompt setup, chatbot integration, and automation.",
    includes: ["Chatbots", "Prompt kits", "Basic automation"],
    idealFor: "Teams exploring AI safely.",
    featured: true,
    categoryTitle: "AI-Based Services",
    visible: true,
  },
]

export const defaultProjects = [
  {
    name: "Global Secure Layer X",
    description: "Security-focused website with clear service messaging and fast load times.",
    industry: "Cybersecurity",
    outcome: "Improved credibility and lead clarity for a security services brand.",
    stack: ["React", "Node.js"],
    featured: true,
    link: "https://globalsecurelayerx.in/",
  },
  {
    name: "Unicus Clothing",
    description: "Modern e-commerce storefront with clean merchandising and mobile-first UI.",
    industry: "Apparel & Retail",
    outcome: "Improved product discovery and a smoother shopping experience.",
    stack: ["React", "Node.js"],
    featured: true,
    link: "https://unicusclothing.com/",
  },
  {
    name: "Operations Hub",
    description: "Internal dashboard to track projects, billing, and delivery health.",
    industry: "Professional services",
    outcome: "Improved visibility for delivery and finance teams.",
    stack: ["React", "Node.js", "MongoDB"],
    featured: true,
    link: "https://example.com",
  },
  {
    name: "Client Intake Portal",
    description: "Secure onboarding flow with automated handoffs and status tracking.",
    industry: "B2B SaaS",
    outcome: "Faster intake and consistent handoffs for sales and delivery.",
    stack: ["React", "Express", "MongoDB"],
    featured: true,
    link: "https://example.com",
  },
  {
    name: "Service Management Suite",
    description: "Role-based access and reporting for multi-location teams.",
    industry: "Field services",
    outcome: "Cleaner reporting and clearer accountability across locations.",
    stack: ["React", "Node.js"],
    featured: false,
    link: "https://example.com",
  },
]

export const defaultTrendingProducts = [
  {
    title: "Resume Pro Pack",
    price: 399,
    description: "ATS-optimized resume with clean design and 2 revisions.",
    imageUrl: "https://images.unsplash.com/photo-1516382799247-87df95d790b7?auto=format&fit=crop&w=1200&q=60",
    details: ["ATS-friendly formatting", "2 revision rounds", "Editable source file"],
    active: true,
  },
  {
    title: "Portfolio Lite",
    price: 1499,
    description: "Single-page portfolio with projects, skills, and contact.",
    imageUrl: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=60",
    details: ["1-page layout", "Mobile-first design", "Deployment support"],
    active: true,
  },
  {
    title: "Personal Branding Kit",
    price: 799,
    description: "LinkedIn headline, bio, and highlight reel of skills.",
    imageUrl: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=60",
    details: ["Headline + about section", "Keyword optimization", "Profile tips"],
    active: true,
  },
  {
    title: "Personalized Gift Page",
    price: 999,
    description: "Custom page with photos, notes, and a sharable link.",
    imageUrl: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=60",
    details: ["Photo gallery", "Custom message", "Shareable link"],
    active: true,
  },
  {
    title: "Pitch Deck Design",
    price: 1299,
    description: "Modern 8–10 slide deck with your content formatted.",
    imageUrl: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=60",
    details: ["8–10 slides", "Clean visual hierarchy", "Editable PPT"],
    active: true,
  },
  {
    title: "Mini Project Build",
    price: 2499,
    description: "End-to-end mini project for college submissions.",
    imageUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=60",
    details: ["Docs + demo", "Source code", "Delivery support"],
    active: true,
  },
]

export const defaultSiteContent = {
  about: {
    heroTitle: "Small team, serious delivery",
    heroSubtitle:
      "We are a focused group of engineers and product strategists. Our work is grounded in honesty, simple execution, and measurable progress.",
    galleryImages: ["/images/about-1.svg", "/images/about-2.svg", "/images/about-3.svg"],
    approach: [
      {
        title: "Discovery",
        description: "We define scope, outcomes, risks, and a practical roadmap.",
      },
      {
        title: "Delivery",
        description: "Weekly updates, tight feedback loops, and clear milestones.",
      },
      {
        title: "Stewardship",
        description: "We document, maintain, and improve the system after launch.",
      },
    ],
    team: [
      {
        name: "Uday Chandra",
        role: "Founder & Delivery Lead",
        bio: "Focused on clear scope, dependable execution, and long-term maintainability.",
        imageUrl: "",
      },
      {
        name: "Vaani Sharma",
        role: "Product & Client Strategy",
        bio: "Focused on clear scope, dependable execution, and long-term maintainability.",
        imageUrl: "",
      },
      {
        name: "Nitesh Pal",
        role: "Engineering & Systems",
        bio: "Focused on clear scope, dependable execution, and long-term maintainability.",
        imageUrl: "",
      },
    ],
    closingNote:
      "We work best with teams who value clear communication, respect time, and want solutions that last. If that sounds like you, we should talk.",
  },
  contact: {
    heroTitle: "Tell us about your project",
    heroSubtitle: "Share your goals and timelines. We will reply with clear next steps.",
    email: "hello@techservices.agency",
    whatsappUrl: "https://wa.me/1234567890",
    locationText: "We are based in the US and work remotely.",
    nextSteps: [
      "We review your request.",
      "We confirm scope and priorities.",
      "You get a clear plan and timeline.",
    ],
    requirements: [
      "A short description of the project.",
      "Expected deadline or milestone.",
      "Current links, docs, or references.",
    ],
  },
  home: {
    heroCards: [],
  },
}
